### ISSUE TITLE
Total nothing

### ISSUE THREAD

**Issue by ontwikkelfabriek** [totaljs/emptyproject-designer#1]
Installed and run the project as documented.

It shows a `Appbuilder` text in the left corner and some empty white panels.

**Comment by petersirka** [comment]
Can you send me a screenshot?

**Comment by ontwikkelfabriek** [comment]
[https://pasteboard.co/JKobeRY.png](url)

**Comment by petersirka** [comment]
I understand. Locally is a bit complicated to use AppBuilder, but it works - just follow:

__Local development__:
- you need to drag & drop file `/builds/app.build` to https://builder.totaljs.com
- then you can modify it in AppBuilder and download the `build` file again

__I recommend__:

- install Total.js SuperAdmin on your Linux server
- or use __Total.js Cloud__ with preinstalled Total.js SuperAdmin <https://www.youtube.com/watch?v=pG1XhlnHoD0>

### Usage in our open-source apps:

__Total.js Code Editor__:

![Total.js Code](https://user-images.githubusercontent.com/2414252/105069969-f0f88800-5a82-11eb-9ae2-d36c2adb27f1.gif)

__Total.js SuperAdmin__:
![SuperAdmin](https://user-images.githubusercontent.com/2414252/105069658-8cd5c400-5a82-11eb-8d72-55368a21471b.png)

**Comment by petersirka** [comment]
I forgot the most important link to __the documentation__:
https://docs.totaljs.com/builder/7708d002mm50c/

**Comment by ontwikkelfabriek** [comment]
Ok, this is totally not understandable what is what. I just wanted to see a demo of your product. ( designer/appbuilder/superadmin or whatever it is)

**Comment by petersirka** [comment]
But 100x sorry - I looked badly at your screenshot and the name of this repository :-D. You have tested AppDesigner (not AppBuilder) :-( ... I found a bug with icons. Please download the example again. At the bottom of the left panel are four icons. Click on the second icon and then create a design. It's beta, and this designer is not officially released because I work on it.

---

I totally understand, but it's not easy to test it locally.

- SuperAdmin is a process manager for Total.js apps (it needs linux server, it generates SSL certificates, etc.), you can test it in Total.js Cloud only or in your own server
- AppBuilder can render `build` and modify it, but you need to have some environment for it e.g. Total.js Code or Total.js SuperAdmin
- you can test locally e.g. Total.js CMS or Total.js Flow

Let me know if you will have any questions.

**Comment by ontwikkelfabriek** [comment]
Yes it works now! Thanks for the help.
